// In: app/src/db/index.ts

import { drizzle } from 'drizzle-orm/expo-sqlite';
import { openDatabaseSync } from 'expo-sqlite';
import { useMigrations } from 'drizzle-orm/expo-sqlite/migrator';
import { Platform } from 'react-native';

// This file is generated by Drizzle Kit and contains all migration definitions.
// We are using a '.js' file because generated files are not always TypeScript.
// Drizzle Kit will manage this file automatically.
import migrations from '../../drizzle/migrations/migrations.js';

/**
 * Opens the synchronous database connection using expo-sqlite.
 * The 'kithkeep.db' file will be created in the app's document directory.
 */
const expoDb = openDatabaseSync('kithkeep.db');

/**
 * The main Drizzle database instance.
 * This is what the rest of the app will use to query the database.
 */
export const db = drizzle(expoDb);

/**
 * A custom React Hook to manage database initialization and migrations.
 * This hook should be used once, at the root of the application,
 * to ensure the database is ready before the app is used.
 *
 * @returns {object} An object containing:
 * - `isDbLoading`: A boolean indicating if migrations are running.
 * - `dbError`: An error object if migrations failed, otherwise null.
 */
export const useDatabaseInitialization = () => {
  const { success, error } = useMigrations(db, migrations);

  if (error) {
    // This is a critical error, the app cannot function.
    // In a real app, this should be logged to a crash reporting service.
    console.error('Database migration error:', error);
    // You could throw the error to stop app execution if needed
    // throw error; 
  }

  // Log the status only in development mode for debugging.
  if (__DEV__ && Platform.OS !== 'web') {
    if (success) {
      console.log('Database migrations applied successfully!');
    }
  }

  return {
    isDbLoading: !success && !error,
    dbError: error,
  };
};